-- +goose Up
CREATE ROLE app_user NOLOGIN;
GRANT app_user TO CURRENT_USER;
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
-- +goose Down
REVOKE app_user FROM CURRENT_USER; DROP ROLE app_user;
