// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, display_name, phone, created_at, last_seen FROM users WHERE id = $1
`

// sqlc queries for the users feature (Task 3 adds the real set).
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}
