// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, phone, created_at FROM users WHERE id = $1
`

type GetUserRow struct {
	ID          pgtype.UUID
	Email       string
	DisplayName []byte
	Phone       []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const syncUser = `-- name: SyncUser :exec

INSERT INTO users(id, email) VALUES($1, $2)
ON CONFLICT (id) DO UPDATE SET email = $2, last_seen = now()
`

type SyncUserParams struct {
	ID    pgtype.UUID
	Email string
}

// sqlc queries for the users feature.
func (q *Queries) SyncUser(ctx context.Context, arg SyncUserParams) error {
	_, err := q.db.Exec(ctx, syncUser, arg.ID, arg.Email)
	return err
}
