// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Invite struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Email      string
	Role       string
	Token      string
	AcceptedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Membership struct {
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	TenantID  pgtype.UUID
	Name      string
	Plan      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName []byte
	Phone       []byte
	CreatedAt   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
}
