// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName []byte
	Phone       []byte
	CreatedAt   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
}
