// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :execrows
UPDATE invites SET accepted_at = now()
WHERE token = $1 AND accepted_at IS NULL
`

func (q *Queries) AcceptInvite(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvite, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addMember = `-- name: AddMember :exec
INSERT INTO memberships(tenant_id, user_id, role) VALUES($1, $2, $3)
`

type AddMemberParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.TenantID, arg.UserID, arg.Role)
	return err
}

const changeRole = `-- name: ChangeRole :execrows
UPDATE memberships SET role = $3 WHERE tenant_id = $1 AND user_id = $2
`

type ChangeRoleParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
	Role     string
}

func (q *Queries) ChangeRole(ctx context.Context, arg ChangeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeRole, arg.TenantID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM memberships WHERE tenant_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one

INSERT INTO invites(tenant_id, email, role, token, expires_at)
VALUES($1, $2, $3, $4, $5)
RETURNING id, tenant_id, email, role, token, accepted_at, expires_at, created_at
`

type CreateInviteParams struct {
	TenantID  pgtype.UUID
	Email     string
	Role      string
	Token     string
	ExpiresAt pgtype.Timestamptz
}

// Invites. CreateInvite/RevokeInvite run inside the org's tenant tx;
// InviteByToken deliberately runs as the pool owner (the token is the
// capability — Accept resolves the tenant from the row).
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one

INSERT INTO orgs(name) VALUES($1)
RETURNING tenant_id, name, plan, created_at
`

// sqlc queries for the orgs feature. Tenant-scoped statements run inside
// WithTenantTx (RLS filters by app.current_tenant); membership resolution
// (MemberRole, ListUserOrgs) deliberately runs as the pool owner.
func (q *Queries) CreateOrg(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, name)
	var i Org
	err := row.Scan(
		&i.TenantID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const expireStaleInvites = `-- name: ExpireStaleInvites :execrows
DELETE FROM invites WHERE accepted_at IS NULL AND expires_at < now()
`

func (q *Queries) ExpireStaleInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrg = `-- name: GetOrg :one
SELECT tenant_id, name, plan, created_at FROM orgs WHERE tenant_id = $1
`

func (q *Queries) GetOrg(ctx context.Context, tenantID pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, tenantID)
	var i Org
	err := row.Scan(
		&i.TenantID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const inviteByToken = `-- name: InviteByToken :one
SELECT id, tenant_id, email, role, token, accepted_at, expires_at, created_at
FROM invites WHERE token = $1
`

func (q *Queries) InviteByToken(ctx context.Context, token string) (Invite, error) {
	row := q.db.QueryRow(ctx, inviteByToken, token)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.AcceptedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT user_id, role, created_at FROM memberships
WHERE tenant_id = $1 ORDER BY created_at, user_id
`

type ListMembersRow struct {
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListMembers(ctx context.Context, tenantID pgtype.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(&i.UserID, &i.Role, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrgs = `-- name: ListUserOrgs :many
SELECT m.tenant_id, o.name, m.role FROM memberships m
JOIN orgs o ON o.tenant_id = m.tenant_id
WHERE m.user_id = $1 ORDER BY o.name
`

type ListUserOrgsRow struct {
	TenantID pgtype.UUID
	Name     string
	Role     string
}

func (q *Queries) ListUserOrgs(ctx context.Context, userID pgtype.UUID) ([]ListUserOrgsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrgsRow
	for rows.Next() {
		var i ListUserOrgsRow
		if err := rows.Scan(&i.TenantID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberRole = `-- name: MemberRole :one
SELECT role FROM memberships WHERE tenant_id = $1 AND user_id = $2
`

type MemberRoleParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) MemberRole(ctx context.Context, arg MemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, memberRole, arg.TenantID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM memberships WHERE tenant_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	TenantID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
DELETE FROM invites WHERE id = $1 AND tenant_id = $2
`

type RevokeInviteParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs SET name = $2 WHERE tenant_id = $1
RETURNING tenant_id, name, plan, created_at
`

type UpdateOrgParams struct {
	TenantID pgtype.UUID
	Name     string
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.TenantID, arg.Name)
	var i Org
	err := row.Scan(
		&i.TenantID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}
